#ifndef USR_CONFIG_H
#define USR_CONFIG_H

// Render
#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_BUFFER_SIZE (DISPLAY_WIDTH * DISPLAY_HEIGHT / 8)
#define BACKGROUND_IMAGE_PATH "/background.bmp"
#define DISPLAY_TYPE U8G2_SSD1306_128X64_NONAME_F_HW_I2C

#define SDA_PIN 21
#define SCL_PIN 22

// WIFI
#define WIFI_SSID "INSERT YOUR WIFI NAME"
#define WIFI_PASSWORD "INSERT YOUR WIFI PASS"

// Telegram
#define BOT_TOKEN "INSERT YOUR TOKEN"

#endif